//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lottery_step1
    {
        public int lottery_id { get; set; }
        public Nullable<int> lottery_num_1 { get; set; }
        public Nullable<int> lottery_num_2 { get; set; }
        public Nullable<int> lottery_num_3 { get; set; }
        public Nullable<int> lottery_num_4 { get; set; }
        public Nullable<int> lottery_num_5 { get; set; }
        public string winner { get; set; }
    }
}
